nextcloud/fulltextsearch

- CHANGELOG.md
- appinfo/info.xml
- js/settings.admin.js
- lib/AppInfo/Application.php
- lib/Command/Check.php
- lib/Command/Clear.php
- lib/Command/Scan.php
- lib/Controller/SettingsController.php
- lib/Events/FilesEvents.php
- lib/Hooks/FilesHooks.php
- lib/Provider/SearchProvider.php
- lib/Service/ConfigService.php
- lib/Service/FileService.php
- lib/Service/SolrService.php
- templates/settings.admin.php
* New format: opendocument, office, rtf, html, epub, ...
* Search within shared file,
* Testing field before saving configuration
* new command: nextant:clear and nextant:check
> merge 0.2.0

- lib/Service/FileService.php
files dont always follow the nice `/path/to/nc/data/$path` format
> More robust way to get the local absolute path of a file

- README.md
Add information about the Nextant scripted installation from the Nextcloud VM.
> Add scripted installation

- README.md
Whoops, I let that one through.
> Had link/text around the wrong way on 1 line of the readme

- js/navigate.js
See https://github.com/nextcloud/server/pull/5959
cc @daita
> Logo claim is not used anymore

- lib/Db/IndexesRequestBuilder.php
just to be sure. Should fix #418
> using TArrayTools

- lib/Service/IndexService.php
Not sure why it is needed, but it should fix #416
> initiate a DocumentAccess - #416

- lib/Command/Index.php
- lib/Command/Test.php
- lib/Db/IndexesRequest.php
- lib/Model/ProviderIndexes.php
- lib/Provider/TestProvider.php
- lib/Service/CliService.php
- lib/Service/IndexService.php
> index by chunks

- lib/Db/TickRequestBuilder.php
> use TArrayTools to parse Tick from db

- lib/Service/ProviderService.php
Signed-off-by: Maxence Lange <maxence@artificial-owl.com>
> filter providers per nc version

- lib/Service/PlatformService.php
> fixing issue

- lib/AppInfo/Application.php
> shorter label 'Search'

- lib/Command/DocumentProvider.php
- lib/Service/IndexService.php
> Add known index if provider returns a document with no index

- lib/Db/IndexesRequest.php
- lib/Model/ProviderIndexes.php
> indexId as key in index list

- lib/Cron/Index.php
> ignore live index on cron

- lib/Search/UnifiedSearchProvider.php
> better parsing of route

- js/fulltextsearch.v1.navigation.js
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>
> l10n: Replace the apostrophe with double quotation

- lib/Service/SearchService.php
> Using CirclesManager

- .scrutinizer.yml
- l10n/fr.js
- l10n/fr.json
- lib/Migration/Version2000Date20201208130255.php
switching filed type to text should fix #678
> convert message to text

- CHANGELOG.md
- Makefile
- appinfo/info.xml
Signed-off-by: Joas Schilling <coding@schilljs.com>
> Update version on master

- lib/Command/DocumentProvider.php
fix a glitch in the displayed result
> replace displayed owner

- lib/Db/IndexesRequest.php
- lib/Migration/Version2401Date202301170001.php
- lib/Model/Index.php
- lib/Service/CollectionService.php
this fix an issue with oracle that set empty string as null
> default collection is local

- lib/Service/PlatformService.php
If there is a problem loading FTS providers (like Elasticsearch), the UI dropdown just stays empty. To allow an admin to further investigate, it would make sense to log the error.
This PR introduces:
* Error logging if loading a FTS provider failed
* Using new `Psr` container interfaces in the `PlatformService` class
> Improve logging when trying to load platforms

- lib/Service/TestService.php
* Adjust tests to cover https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/265
* Tests would fail if SearchPlatform is not filtering the results case sensitively
Basically testing the changes from:
* https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/237
* https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/265
> Adjust username and group for keyword search

- lib/Command/Test.php
- lib/Service/TestService.php
> more login to test

- lib/Command/CollectionList.php
- lib/Command/Reset.php
- lib/Db/IndexesRequest.php
- lib/Service/CollectionService.php
- lib/Service/IndexService.php
- fixing some issue introduced by #776
- reset now asks for confirmation
- manage single collection reset
> collections and reset

- lib/Db/CoreRequestBuilder.php
> remove useless ref

- lib/Command/Index.php
- lib/Command/Live.php
- lib/Cron/Index.php
- lib/Exceptions/PlatformTemporaryException.php
- lib/Service/IndexService.php
> [stable27] PlatformTemporaryException

- lib/Command/Index.php
- lib/Command/Live.php
- lib/Cron/Index.php
- lib/Exceptions/PlatformTemporaryException.php
- lib/Service/IndexService.php
> [stable26] PlatformTemporaryException

- lib/Migration/Version2801Date202309200001.php
> manage error on duplicate/deprecated index

- lib/AppInfo/Application.php
* Fix https://github.com/nextcloud/fulltextsearch/issues/842
* Alternative for https://github.com/nextcloud/server/pull/47196
> fix: Add navigation entry by closure

- appinfo/info.xml
Signed-off-by: Joas Schilling <coding@schilljs.com>
> feat(deps): Add Nextcloud 30 support on master

- lib/Command/CollectionLink.php
newly added file was lacking the SPDX header making the reuse check fail
> Add SPDX header

- lib/AppInfo/Application.php
Fix is done as suggested by customer
> fix(Application): translate name of app search

- lib/Db/CoreRequestBuilder.php
- lib/Db/IndexesRequest.php
- lib/Db/TickRequest.php
Index can be an _extremely_ long process, and connection to the database might be interrupted/lost during that time.
This will try to reconnect for 5 minutes, instead of crashing instantly.
> feat(database): reconnect on lost connection
